### ISSUE TITLE
'TextFileReader' object has no attribute 'dropna' error when opening a spreadsheet

### ISSUE THREAD

**Issue by mikehedman** [esper-io/esper-api-support-tool#156]
User clicked on the open spreadsheet icon, uploaded a spreadsheet (attached), and got this error:
![image](https://github.com/esper-io/esper-api-support-tool/assets/1550290/a879f197-7228-4b44-a99b-e6433ccf3840)

[serial - Copy of MASTER (15).csv](https://github.com/esper-io/esper-api-support-tool/files/14938679/serial.-.Copy.of.MASTER.15.csv)

Version: 
![image](https://github.com/esper-io/esper-api-support-tool/assets/1550290/ca947d24-244b-4c20-9d21-98e6bc34e2d8)

**Comment by jonathan-esper** [comment]
Upload issue should now be addressed as part of the following release: https://github.com/esper-io/esper-api-support-tool/releases/tag/v0.195242
