### ISSUE TITLE
Remove security related info from main page

### ISSUE THREAD

**Issue by mikehedman** [esper-io/esper-api-support-tool#157]
As I was uploading a screenshot, I realized that our API Key and Enterprise id were visible in plain text.  Seems like it would be best to not have these visible all the time (or ever).
<img width="402" alt="image" src="https://github.com/esper-io/esper-api-support-tool/assets/1550290/dd31adb4-99f5-42d6-8803-ef81a05e3aff">

**Comment by jonathan-esper** [comment]
Enterprise ID and API Token should now be removed from view as the following release: https://github.com/esper-io/esper-api-support-tool/releases/tag/v0.195242
