### ISSUE TITLE
Device information empty

### ISSUE THREAD

**Issue by bcookatpcsd** [esper-io/esper-api-support-tool#162]
Thank you for this.. 

Everything seems to be loaded, I am able to get reports (xlsx) but I do not see any device information in the main screen.

Your documentation:
![image](https://github.com/esper-io/esper-api-support-tool/assets/55087301/8895e550-1b0e-4e78-a9df-0df301436be1)

My window:
![image](https://github.com/esper-io/esper-api-support-tool/assets/55087301/4151ebfd-8566-47e2-9e24-f8b6e4c7c5b3)

Am I missing something? 

Thank you in advance.

**Comment by jonathan-esper** [comment]
@bcookatpcsd For that report generation, I see in the screenshot that you have selected the option for App Report. This will only populate the "Application Information" sheet, which is intended.

For device information, you will need to use either:
- Device Report
    - This report will give information obtained by the standard Device API (mostly static info).
- Device & Network Report
    - Includes the above info and information from the Latest Event API (mostly dynamic info). 
- All reports
    - Populates all sheets. 

Please let me know if this was not the case.
