### ISSUE TITLE
Feature request: Add "Clear App Data" to grid actions

### ISSUE THREAD

**Issue by mikehedman** [esper-io/esper-api-support-tool#166]
We are needing to clear the app cache on a large number of devices which are not all within one group.  It would be nice to be able to upload a CSV of the device list, and Clear App Data.  Hopefully since there's an Uninstall App option, adding Clear App Data wouldn't be too hard.
Thanks

**Comment by mikehedman** [comment]
Hmm, I just downloaded the most recent build (195246), and it looks like the application actions are gone entirely now. I'm no longer seeing the Clear App Data action anywhere:
![mac_arm64_v0-194898_EsperApiSupportTool 2024-07-31 12 00 29](https://github.com/user-attachments/assets/2829df57-86ff-412e-b3b0-813aec3a452d)

**Comment by jonathan-esper** [comment]
Certain features were removed due to low usage and possible concern on risk factor in a previous release (https://github.com/esper-io/esper-api-support-tool/releases/tag/v0.19522).
